#!/usr/bin/env bash
HERE=$(dirname "$(readlink -f "$0")")
export NP_LOCATION="$HERE/.nix-store"
# export NP_RUNTIME="$HERE/deps/bwrap/bwrap"
export NP_RUNTIME="bwrap"
export NP_GIT=$(which git)

"$HERE/nix-portable" nix run "$HERE#" -- "$@"

